FROM ubuntu
MAINTAINER Ramon Brooker <rbrooker@aetherealmind.com>

ENV DEBIAN_FRONTEND noninteractive


RUN cat /etc/resolv.conf



RUN apt-get update --print-uris 

CMD ["bash"]

# Install Updates, and other needed prgms
#RUN apt-get update ; apt-get -y install logrotate wget apt-utils; apt-get -y upgrade



