# Written By: Ramon Brooker <rbrooker@aetherealmind.com>
# # (c) 2016
#
# 

version: '2'
services: 
  bigwig:
    image: rbrooker/rabbitmq:3.6.4-1
    container_name: bigwig
    hostname: "bigwig"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbit/etc:/etc/rabbitmq
      - ./rabbit/logs:/var/log/rabbitmq
      - ./rabbit-config-volume:/custom_config
    environment:
      - FEDERATION=1
      - LOG_LEVEL="{connection,error},{channel,error},{federation,error}" 
      - SSL="false"
  hazel:
    image: rbrooker/rabbitmq:3.6.4-1
    ports:
      - "6672:6672"    
    links:
      - bigwig:bigwig
    container_name: hazel
    hostname: "hazel"
    environment:
      - AMQP_TCP_PORT=6672
      - SSL_TCP_PORT=6671
      - MASTER_NAME=bigwig
      - FEDERATION=1
      - MASTER=0
      - NODE_TYPE="ram"
      - SSL="false"
    volumes:
      - ./rabbit/logs:/var/log/rabbitmq
  fiver:
    image: rbrooker/rabbitmq:3.6.4-1
    ports:
      - "7672:7672"    
    links:
      - bigwig:bigwig
    container_name: fiver
    hostname: "fiver"
    environment:
      - AMQP_TCP_PORT=7672
      - SSL_TCP_PORT=7671
      - MASTER_NAME=bigwig
      - MASTER=0
      - FEDERATION=1
      - SSL="false"
    volumes:
      - ./rabbit/logs:/var/log/rabbitmq
  lord-frith:
    image: rbrooker/rabbitmq:3.6.4-1
    ports:
      - "8672:8672"    
      - "18672:18672"
    links:
      - bigwig:bigwig
      - fiver:fiver
      - hazel:hazel  
    container_name: lord-frith
    hostname: "lord-frith"
    environment:
      - AMQP_TCP_PORT=8672
      - SSL_TCP_PORT=8671
      - MANAGEMENT_PORT=18572
      - MASTER_NAME=bigwig
      - FEDERATION=1
      - MASTER=1
      - CLUSTERED=1
      - SSL="false"
    volumes:
      - ./rabbit/logs:/var/log/rabbitmq
  
